---

repos:
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.7.0  # release tag from https://github.com/ansible-community/ansible-lint/releases/
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: (^travis.yml$)
        stages: ["commit"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: ["commit-msg"]
