---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check gpgtar
      block:
        - name: Register gpgtar
          ansible.builtin.stat:
            path: "{{ ansible_user_dir }}/bin/gpgtar"
          register: gpgtar
        - name: Assert gpgtar exists
          ansible.builtin.assert:
            that: gpgtar.stat.exists
